---

- name: grab host's machine id
  ansible.builtin.slurp:
    src: /etc/redhat-access-insights/machine-id
  register: machine_id

- name: asign a host to a compliance policy
  block:
    - name: get all compliance policies
      ansible.builtin.uri:
        url: https://cloud.redhat.com/api/compliance/profiles
        force_basic_auth: true
        user: "{{ lookup('env', 'CRHC_USERNAME') }}"
        password: "{{ lookup('env', 'CRHC_PASSWORD') }}"
        method: GET
      register: compliance_policies

    - name: search for host's insights id
      ansible.builtin.uri:
        url: "https://cloud.redhat.com/api/inventory/v1/hosts?insights_id={{ machine_id['content'] | b64decode }}"
        force_basic_auth: true
        user: "{{ lookup('env', 'CRHC_USERNAME') }}"
        password: "{{ lookup('env', 'CRHC_PASSWORD') }}"
        method: GET
      register: insights_host_info

    - name: set insights ID fact
      ansible.builtin.set_fact:
        insights_id: "{{ insights_host_info.json | ansible.builtin.json_query('results[*].id') | join() }}"

    - name: get policy id
      ansible.builtin.set_fact:
        policy_id: "{{ policy.id }}"
      when:
        - policy.attributes.name == policy_name
        - policy.attributes.os_version == ansible_distribution_major_version | string
      loop_control:
        loop_var: policy
      loop: "{{ compliance_policies.json.data }}"
      no_log: true

    - name: add up existing hosts and new host
      ansible.builtin.set_fact:
        policy_hosts: "{{ policy.relationships.hosts.data + [{'id': insights_id, 'type': 'host'}]  }}"
      when:
        policy_id == policy.id
      loop_control:
        loop_var: policy
      loop: "{{ compliance_policies.json.data }}"
      no_log: true

    - name: update policy with new host
      ansible.builtin.uri:
        url: "https://cloud.redhat.com/api/compliance/profiles/{{ policy_id }}"
        force_basic_auth: true
        user: "{{ lookup('env', 'CRHC_USERNAME') }}"
        password: "{{ lookup('env', 'CRHC_PASSWORD') }}"
        method: PATCH
        body_format: json
        body:
          data:
            relationships:
              hosts:
                data: "{{ policy_hosts }}"
  delegate_to: localhost
